animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']
puts "The animal at 1: #{animals[1]}"
puts "The 3rd animal: #{animals[2]}"
puts "The 1st animal: #{animals[0]}"
puts "The animal at 3: #{animals[3]}"
puts "The 5th animal: #{animals[4]}"
puts "The animal at 2: #{animals[2]}"
puts "The 6th animal: #{animals[5]}"
puts "The animal at 4: #{animals[4]}"
puts "The 5th animal: #{animals.last}"